#colors
defColor = "blue"
quoteColor = "green"
commentColor = "grey"
importColor = "light blue"
varColor = "Orange"
bgColor = "black"
fgColor = "white"
insertColor = "white"
keyColor = "yellow"
selfColor = "white"
argColor = "brown"
tempColor = "red"